// export const ActionTypes = {
//     FETCH_PRODUCTS:"FETCHPRODUCTS",
//     SET_PRODUCTS: "SET_PRODUCTS",
//     SELECTED_PRODUCT: "SELECTED_PRODUCT",
//     REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
//   };

export const ActionType={
  ADD_POST:"ADDPOST"
  , 
  VIEW_POSTS:"VIEWPOST"
  , 
  SORT_POSTS:"SORTPOST",
  
  UPVOTE_COMMENT:"UPWARDACTION",
   DOWNVOTE_COMMENT:"DOWNWARDACTION",
}
;